channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip

  - pytorch>=1.12.1
  - torchvision
  - pytorch-lightning
  - transformers
  - datasets>=2.0.0

  - pandas
  - scikit-learn

  - rich
  - typer
  - wandb
  - loguru
  - zstandard

  - black
  - flake8
  - flake8-bugbear
  - isort
  - mypy
  - pre-commit

  - pip:
      - pytorch_optimizer
